In [55]:
# https://medium.com/@hjhuney/implementing-a-random-forest-classification-model-in-python-583891c99652

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import model_selection
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import RandomizedSearchCV

results.loc[(results['pred_in_direction'] == 'left') & (results['pred_out_direction'] == 'left'),'predict'] = 0
results.loc[(results['pred_in_direction'] == 'left') & (results['pred_out_direction'] == 'right'),'predict'] = 1
results.loc[(results['pred_in_direction'] == 'right') & (results['pred_out_direction'] == 'left'),'predict'] = 2
results.loc[(results['pred_in_direction'] == 'right') & (results['pred_out_direction'] == 'right'),'predict'] = 3

y = results['predict'].copy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=62)

# random forest model creation
rfc = RandomForestClassifier(n_estimators=1400, max_depth=100, max_features='auto')
rfc.fit(X_train,y_train)
# predictions
rfc_predict = rfc.predict(X_test)

rfc_cv_score = cross_val_score(rfc, X, y, cv=6)

print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, rfc_predict))
print('\n')
print("=== Classification Report ===")
print(classification_report(y_test, rfc_predict))

print("=== All AUC Scores ===")
print(rfc_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ", rfc_cv_score.mean())

"""
# number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# number of features at every split
max_features = ['auto', 'sqrt']

# max depth
max_depth = [int(x) for x in np.linspace(100, 500, num = 11)]
max_depth.append(None)
# create random grid
random_grid = {
 'n_estimators': n_estimators,
 'max_features': max_features,
 'max_depth': max_depth
 }
# Random search of parameters
rfc_random = RandomizedSearchCV(estimator = rfc, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the model
rfc_random.fit(X_train, y_train)
# print results
print(rfc_random.best_params_)
"""


=== Confusion Matrix ===
[[2 1 0]
 [1 8 0]
 [2 0 7]]


=== Classification Report ===
              precision    recall  f1-score   support

         0.0       0.40      0.67      0.50         3
         1.0       0.89      0.89      0.89         9
         2.0       1.00      0.78      0.88         9

   micro avg       0.81      0.81      0.81        21
   macro avg       0.76      0.78      0.75        21
weighted avg       0.87      0.81      0.83        21

=== All AUC Scores ===
[0.90909091 0.81818182 1.         0.90909091 1.         0.66666667]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.883838383838384


"\n# number of trees in random forest\nn_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]\n# number of features at every split\nmax_features = ['auto', 'sqrt']\n\n# max depth\nmax_depth = [int(x) for x in np.linspace(100, 500, num = 11)]\nmax_depth.append(None)\n# create random grid\nrandom_grid = {\n 'n_estimators': n_estimators,\n 'max_features': max_features,\n 'max_depth': max_depth\n }\n# Random search of parameters\nrfc_random = RandomizedSearchCV(estimator = rfc, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)\n# Fit the model\nrfc_random.fit(X_train, y_train)\n# print results\nprint(rfc_random.best_params_)\n"